const Discord = require('discord.js')

module.exports = {
    name: "kill",
    description: "De quel manière vas-tu tuer ton ami ?",
    permission: "Aucune",
    dm: false,
    category: "fun",

    options: [
        {
            type: "user",
            name: "membre",
            description: "Le membre à tuer",
            required: true,
            autocomplete: true

        },
    ],

    async run(client, message, args) {

        const user = message.options.getUser('membre');

        if (!user) return message.reply("kill [utilisateur]");

        var kills = [
            ` après une sale journée, se pose sur le canap avec ${user} et mate The Big Bang Theory. Après une vanne de Sheldon Cooper, ${user} lâche son meilleur fou rire et claque sur place.`,
            `${message.user} a fait Alt+F4 sur ${user}.exe !`,
            `${message.user} a tenté un solo de flûte, la tête de ${user} a littéralement explosé.`,
            `${message.user} s'est détruit les tympans en écoutant de la musique un peu trop déter.`,
            `${message.user} provoque ${user} dans un octogone sans règles à mort. ${user} gagne.`,
            `${message.user} découpe la tête de ${user} à coups de clavier.`,
            `${message.user} atomise ${user} avec un frigo.`,
            `${message.user} décapite ${user} au sabre.`,
            `${message.user} a trop tiré sur les oreilles de ${user} et les a arrachées.`,
            `${message.user} noie ${user} dans un tonneau de bière.`,
            `${message.user} noie ${user} dans un bac de chocolat chaud. *Alors, elle était bonne la dernière goutte ?*`,
            `${message.user} éviscère ${user} avec un couteau à beurre tout rouillé. Aïe !`,
            `${message.user} fait bouffer des Oreos au dentifrice à ${user}, qui était visiblement allergique au fluor. GGWP.`,
            `${message.user} est tombé love de ${user} avant de lui briser le cœur... littéralement.`,
            `${message.user} propulse une dinde congelée supersonique sur ${user} et le couche net.`,
            `${message.user} a oublié de laisser la vitre de la caisse ouverte, ${user} est mort en mode cuisson interne.`,
            `${message.user} a oublié de sécuriser le jardin de ${user} contre les zombies... On dirait bien qu'ils se sont fait un buffet géant hier soir.`,
            `${message.user} a forcé ${user} à mater des animés avec lui. ${user} a fait une surdose.`,
            `${message.user} attrape ${user}, le jette dans un congélateur industriel avec du jus et cale la température à 100 Kelvin. Bim, des Mister Freeze humains.`,
            `${message.user} m'a payé pour te fumer, mais flemme en vrai ! ${user}`,
            `${message.user} fait un câlin un peu trop violent à ${user}...`,
            `${message.user} fracasse ${user} en mode Hulk et le transforme en purée.`,
            `${message.user} a tué ${user} en lui arrachant la peau du visage pour s'en faire un masque.`,
            `${message.user} achève ${user} après des heures de torture.`,
            `${message.user} bute ${user} avec un chandelier dans le grand salon.`,
            `${message.user} tue ${user} avec trop de gentillesse.`,
            `${message.user} tue ${user} avec son propre pied.`,
            `${message.user} découpe ${user} à la hache.`,
            `${message.user} a appuyé sur Suppr. Ça a supprimé ${user}.`,
            `${message.user} éjecte ${user} dans le vide glacial de l'espace.`,
            `${message.user} roule sur ${user} avec une PT Cruiser.`,
            `${message.user} met une balle dans la tête de ${user}.`,
            `${message.user} tire un laser arc-en-ciel dans la bouche de ${user}, faisant exploser sa tête en confettis. ${user} réapparaît en licorne. :unicorn:`,
            `${message.user} a désintégré ${user} avec la base Starkiller !`,
            `${message.user} glisse de l'eau de Javel dans la limonade de ${user}.`,
            `${message.user} étrangle ${user}.`,
            `${message.user} ligote ${user} sur un missile balistique direction la Corée du Nord.`,
            `${message.user} lance le sort de la mort sur ${user}... *Avada Kedavra !*`,
            `${message.user} lui arrache les lèvres après un bisou.`,
            `${message.user} est tellement thicc qu'il lui enfonce la cage thoracique.`,
            `${message.user} essaie de viser une grange énorme, rate sa cible et shoote dans ${user} à la place.`,
            `${message.user} met Chair de Poule (le film de 2015) à la TV. ${user}, cette grosse flipette, fait un arrêt cardiaque.`,
            `${message.user} avait tellement de swag que ${user} a cané direct. #Swag`,
            `${message.user}, t'es sûr que tu veux fumer ${user} ? Il a l'air sympa pourtant.`,
            `${user} a cliqué par erreur sur une pub pop-up : \`Les médecins le détestent, découvrez sa technique infaillible pour mourir aujourd'hui !\``,
            `${user} a trébuché comme un bouseux et s'est tué en allant écrire sa lettre d'adieu.`,
            `${user} a mangé un morceau de beurre d'exception. C'était tellement lourd qu'il en est mort.`,
            `${user} a mangé une pomme qui était en fait en cire. Un mort par empoisonnement à la bougie de recensé plus tard dans la journée.`,
            `${user} a pris trop de laxatifs et s'est noyé dans sa propre merde. Crado.`,
            `${user} s'est vidé de son sang en essayant de passer dans l'émission \`Les pires cassos du terroir\`.`,
            `${user} a acheté un hand spinner et s'est noyé sous un tsunami de meufs.`,
            `${user} ne peut pas mourir, c'est déjà un fantôme.`,
            `${user} s'étouffe dans une poubelle.`,
            `${user} s'étouffe avec un os de poulet.`,
            `${user} s'étouffe avec des Cheerios et crève. Quel teubé...`,
            `${user} monte le son à fond pour s'apercevoir que le volume était au max et que la musique c'était Baby de Justin Bieber...`,
            `${user} se prend un jet de foutre dans l'œil, devient aveugle, court chercher de l'aide mais fonce direct sur les rails et se fait rouler dessus par un TER.`,
            `${user} s'est dit que c'était une bonne idée de chauffer un tigre alors qu'il puait la viande. Ça a mal tourné.`,
            `${user} a sorti un mème pas assez dank et s'est fait lapider.`,
            `${user} est mort après s'être astiqué le poireau 50 fois d'affilée sans pause.`,
            `${user} est mort après une session gaming de 90 heures d'affilée sans bouger ni grailler.`,
            `${user} est mort après avoir joué avec un hand spinner customisé avec des lames de rasoir sombres.`,
            `${user} est mort sur le coup en réalisant à quel point son orthographe piquait les yeux.`,
            `${user} est mort en essayant de sortir un meilleur mème que Dank Memer.`,
            `${user} a eu une mort honorable. Mort par le tchic-tchic (snoo snoo).`,
            `${user} est mort parce que RemindMeBot a oublié de lui rappeler de respirer.`,
            `${user} est mort parce qu'il jouait avec un hand spinner avant de capter qu'on est en 2016, du coup il commence à se rincer l'œil sur la vieille sorcière de Blanche-Neige pendant qu'Obama tond sa pelouse, il saute par la fenêtre et se fait découper en morceaux par la tondeuse d'Obama.`,
            `${user} est mort tellement ${message.user} est un génie du mal débile.`,
            `${user} est mort après avoir englouti BEAUCOUP trop de hot-dogs pour se préparer à son date de vendredi soir.`,
            `${user} est mort en mangeant des sushis au poisson cru périmé et infecté avec le riz le plus dégueulasse du monde, tout en se faisant enfoncer un clou de 22 cm ultra aiguisé dans les bourses. La sauce soja c'était du pisse de chat.`,
            `${user} est mort d'une surdose de sel.`,
            `${user} est mort d'un high kick vicieux en plein cerveau.`,
            `${user} est mort après avoir reçu la pire pipe de l'histoire.`,
            `${user} est mort en faisant le Ice Bucket Challenge.`,
            `${user} est mort pour avoir bu trop d'eau. Ah ouais, en fait c'est possible !`,
            `${user} est mort en bouffant des épines de cactus.`,
            `${user} est mort à force de bouffer trop d'anus.`,
            `${user} est mort pour avoir mangé trop de pain. :/`,
            `${user} est mort d'Ebola.`,
            `${user} est mort d'une carence aiguë en mèmes. :/`,
            `${user} est mort parce qu'il n'a pas bouffé assez d'anus.`,
            `${user} est mort parce qu'il s'est pas assez astiqué le manche. (Faut trouver le bon équilibre, les gars).`,
            `${user} est mort pour avoir posté un mème volé dans le mauvais quartier.`,
            `${user} est mort après avoir posé une pêche pendant 36 heures d'affilée.`,
            `${user} est mort en avalant des cailloux trop vite.`,
            `${user} est mort à cause de trop gros coups de soleil.`,
            `${user} est mort parce qu'il s'est trop astiqué le manche. (Faut trouver le bon équilibre, les gars).`,
            `${user} est mort d'un excès de gâterie.`,
            `${user} est mort en testant une bombe H. Y a plus rien à enterrer.`,
            `${user} est mort en écoutant 'It's every day bro'.`,
            `${user} est mort en jouant à la marelle sur des mines *parfaitement* désamorcées.`,
            `${user} est mort en cherchant l'Angleterre sur la carte des villes.`,
            `${user} est mort. CHEH.`,
            `${user} claque après avoir avalé un cure-dent.`,
            `${user} se fait fumer par ${message.user}.`,
            `${user} meurt parce qu'elle a utilisé une épingle à cheveux pour se recourber les cils.`,
            `${user} crève juste parce qu'il avait trop le seum.`,
            `${user} meurt pour avoir lâché un gros mot sur un serveur Minecraft chrétien.`,
            `${user} meurt par manque de potes. Zero vanne.`,
            `${user} meurt d'une mauvaise gâterie.`,
            `${user} crève en lâchant son meilleur dab.`,
            `${user} meurt en dabant trop fort.`,
            `${user} meurt pour avoir manqué de respect aux femmes.`,
            `${user} meurt juste parce que c'est un sale type détestable.`,
            `${user} meurt pour avoir partagé des mèmes de normie.`,
            `${user} meurt à cause de sa haine viscérale du sable. C'est rêche, ça gratte et ça s'infiltre partout.`,
            `${user} meurt après avoir maté le film Emoji et kiffé l'expérience.`,
            `${user} meurt dans un terrible accident orchestré en sous-main par ${message.user}.`,
            `${user} meurt au nord du Mur et se transforme en Marcheur Blanc.`,
            `${user} meurt du SIDA.`,
            `${user} meurt de la dysenterie.`,
            `${user} meurt de causes naturelles.`,
            `${user} meurt de faim.`,
            `${user} finit dans le couloir de la mort et prend son injection létale après avoir découpé ${message.user} et toute sa Mif.`,
            `${user} meurt, mais n'oublions pas qu'en 1998, Undertaker a balancé Mankind du haut de la cage du Hell In A Cell, le faisant fracasser la table des commentateurs 5 mètres plus bas.`,
            `${user} meurt.`,
            `Après une grosse bagarre, ${user} démonte ${message.user}.`,
            `${user} a été purement et simplement effacé de l'univers.`,
            `${user} a bu un soda toxique juste avant le rappel des lots.`,
            `${user} s'est mangé un Nokia 3310 sur le nez, crâne ouvert en deux.`,
            `${user} s'est noyé dans ses propres larmes.`,
            `${user} a bouffé trop de copypasta et a explosé.`,
            `${user} est tombé d'une falaise en jouant à Pokémon Go. GG le nez collé sur ton vieux téléphone de poche. :iphone:`,
            `${user} est tombé dans une fosse remplie de féministes enragées.`,
            `${user} se fait saucer par une voiture.`,
            `${user} se fait planter par ${message.user}.`,
            `${user} se prend la foudre.`,
            `${user} tente une run génocide et Sans lui met la misère de sa vie !`,
            `${user} est parti en duel au couteau avec le Pape. L'un d'eux est actuellement en enfer.`,
            `${user} s'est fait piétiner par un éléphant.`,
            `${user} est mort d'une surdose d'anulingus.`,
            `${user} fait un AVC après une vie de misère bien triste. Il se fait ensuite bouffer par ses douze chats.`,
            `${user} a été reconnu coupable, c'est l'heure de l'exécution !`,
            `${user} a mangé un chinois douteux et l'a payé de sa vie.`,
            `${user} se fait enlever par des aliens, et le gouvernement le liquide pour étouffer l'affaire.`,
            `${user} est mort, tué par ${message.user}.`,
            `${user} s'est fait injecter du sirop de chocolat et a muté en bonhomme en chocolat. Pendant son taf d'appoint à la crèche, il s'est fait dévorer par les bébés morts de faim. :chocolate_bar:`,
            `${user} s'est fait étaler par un lapin psychopathe ultra féroce.`,
            `${user} s'est tué tout seul tellement il est con.`,
            `${user} meurt dans un braquage qui a mal tourné.`,
            `${user} est immortel. Ah, en fait non, ${message.user} le fume quand même.`,
            `${user} est tellement teubé qu'il s'est étouffé avec de l'oxygène.`,
            `${user} s'est fait entasser dans un costume par Freddy pendant son service de nuit. Oh non, pas encore ces foutus animatroniques !`,
            `${user} est aspiré dans Minecraft. ${user}, gros noob sur ce Minecraft "IRL", se prend l'écran de Game Over direct.`,
            `${user} s'est suicidé après avoir vu les mèmes de normie claqués au sol postés par ${message.user}.`,
            `${user} se fout en l'air en réalisant le niveau de stupidité de ${message.user}.`,
            `${user} survit, malgré la tentative de meurtre de ${message.user}.`,
            `${user} perd l'envie de vivre.`,
            `${user} appuie sur un bouton au pif et se fait téléporter à 100m de hauteur, s'offrant une chute fatale inévitable. Morale de l'histoire : arrête de tripoter tous les boutons.`,
            `${user} enchaîne les mèmes jusqu'à ce que mort s'ensuive.`,
            `${user} s'est arraché le cœur...`,
            `${user} s'est arraché le cœur pour prouver son amour à ${message.user}.`,
            `${user} hurle de terreur après avoir invoqué Cthulhu par accident en bafouillant des mots en latin. Cthulhu attrape ${user} par la jambe droite et l'embarque dans sa dimension en criant : \`Chérie, à table !\``,
            `${user} a glissé dans la salle de bain et s'est étouffé avec le rideau de douche.`,
            `${user} glisse sur une peau de banane et dévale les escaliers.`,
            `${user} fait tourner un hand spinner, quand le truc s'arrête, il clamse...`,
            `${user} marche sur un grill George Foreman et meurt d'une infection au pied en forme de gaufre.`,
            `${user} s'est pris une flèche dans le genou. Et partout ailleurs aussi.`,
            `${user} a mal parlé aux modos et s'est fait atomiser par le marteau du ban.`,
            `${user} a incliné son fedora un poil trop loin et est tombé sur les rails alors que le métro arrivait.`,
            `${user} a voulu faire du bricolage mais s'est coupé tout seul comme un grand avec les ciseaux. :scissors:`,
            `${user} a tenté de percer sur YouTube avec un stream complètement débile : du saut en parachute enchaîné à un frigo.`,
            `${user} a tenté de courir plus vite qu'un train. Le train a gagné.`,
            `${user} a tenté de choisir le Saint Graal. Mauvais choix, l'ami.`,
            `${user} a voulu jouer sur la route...`,
            `${user} trébuche sur ses propres lacets et crève.`,
            `${user} a critiqué ouvertement les Clinton puis a soudainement disparu de la circulation.`,
            `${user} habitait sur Alderaan juste avant que Darth Vader ne fasse sauter la planète...`,
            `${user} a été accusé d'avoir volé la couronne de Neptune...`,
            `${user} faisait charger son Samsung Galaxy Note 7...`,
            `${user} s'est fait bouffer vivant par des fourmis.`,
            `${user} a eu l'opportunité de synthétiser l'élément 119 (Ununennium) pour lui donner son nom, mais il a tout foiré. RIP.`,
            `${user} s'est fait fumer par ${message.user} avec des lingettes pour bébé.`,
            `${user} a été assassiné par ${message.user}, tout le monde le sait, mais y a zéro preuve.`,
            `${user} s'est fait éviscérer par ${message.user} et ses entrailles forment maintenant Ennard.`,
            `${user} a été téléporté dans la timeline où Jurassic World existe en vrai et s'est fait bouffer vivant par l'Indominus Rex.`,
            `${user} a été balancé dans le broyeur d'une benne à ordures par ${message.user}.`,
            `${user} marchait tranquillement quand il a aperçu du coin de l'œil un mec faire un bottle flip suivi d'un dab, ce qui lui a déclenché un AVC immédiat.`,
            `${user} a maté le film Emoji et est mort de pur cringe.`,
            `${user} est parti faire un tour dans une montgolfière en plomb.`,
            `Après s'être fait pousser dans l'océan par ${message.user}, ${user} se fait crosser par un requin.`,
            `Après un raid de gamins de Roblox sur le serveur, ${user} a chopé le cancer.`,
            `Le SIDA. ${user} est mort du SIDA.`,
            `En appelant les puissances divines, ${message.user} foudroie ${user} et ses mœurs de païen.`,
            `Contre toute attente, je ne fume **pas** ${user}.`,
            `Miroir magique, c'est toi qui dis qui l'es.`,
            `Notre seigneur et sauveur Gaben foudroie ${user}.`,
            `Désolé ${message.user}, j'aime pas trop fumer des gens.`,
            `La balle a raté Harambe et a touché ${user} à la place. Tant mieux pour Harambe !`,
            `En plein examen de la coloscopie d'un éléphant, ${user} se coince la tête dans le rectum de l'animal et meurt étouffé.`,
        ]
        const embed = new Discord.EmbedBuilder()
            .setColor(client.color)
            .setTitle(`🔫・Kill`)
            .setDescription(`${kills[Math.floor(Math.random() * kills.length)]}`)
            .setTimestamp()
            .setFooter({ text: `${message.user.username}`, iconURL: message.user.displayAvatarURL({ dynamic: true }) })

        await message.reply({ embeds: [embed] });


    }
}

